---
- import_role:
    name: install-docker-plugin
  when: inventory_hostname in groups['hives']
- import_role:
    name: pull-docker-images
  when: inventory_hostname in groups['hives']
# - import_role:
#     name: enable-replication
#   when: inventory_hostname in groups['repository']
# - import_role:
#     name: disable-replication
#   when: inventory_hostname in groups['repository']
