---
plugin: hive_services
services:
  guacamole:
    image:
      from: procube/guacamole
      roles:
        - guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME: /opt/guacamole/
      RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings
      HEADER_ENABLED: "true"
    volumes:
      - source: guacamole-drives
        target: /var/lib/guacamole/drives
        type: volume
      - source: guacamole-recordings
        target: /var/lib/guacamole/recordings
        type: volume
    user: root
    labels:
      published_name: guacamole
      HIVE_MARK: guacamole
    endpoint_mode: dnsrr
  guacd:
    image: procube/guacd
    volumes:
      - source: guacamole-drives
        target: /var/lib/guacamole/drives
        type: volume
        drbd:
          fstype: xfs
          size: 300M
      - source: guacamole-recordings
        target: /var/lib/guacamole/recordings
        type: volume
        drbd:
          fstype: xfs
          size: 20G
    endpoint_mode: dnsrr
    placement:
      constraints:
        - node.labels.guacamole == true
          #- node.labels.repository != true
  guacamole-db:
    image:
      from: postgres:15.2-alpine
      roles:
        - python-aptk
        - guacamole-initdb
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRES_USER: guacamole_user
    volumes:
      - source: guacamole-db
        target: /var/lib/postgresql/data
        type: volume
        drbd:
          fstype: xfs
          size: 5G
    endpoint_mode: dnsrr
    backup_scripts:
      - name: guacamole_db
        backup_command: pg_dump -U guacamole_user -c -C --if-exists guacamole_db | gzip > /root/today.sql.gz
        restore_command: psql -U guacamole_user guacamole_db -f /root/pg-terminate-backend.sql;  zcat /root/today.sql.gz | psql -U guacamole_user postgres
        backup_file: /root/today.sql.gz
        restore_file: /root/today.sql.gz
        ext: sql.gz
        cleanup_days_before: 3
  file-server:
    image: procube/file-server:socket-warp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: "mongodb://files-db:27017/files_db?authSource=admin"
      GUAC_API_URL: http://guacamole:8080/guacamole
      SESSION_MANAGER_URL: http://session-manager:80
      IDM_URL: https://idm.nsag-dev.procube-demo.jp
      WS_URL: wss://file-server.nsag-dev.procube-demo.jp
      LOGOUT_URL: https://file-server.nsag-dev.procube-demo.jp/Shibboleth.sso/Logout
      DOCUMENT_URL: http://document.nsag-dev.procube-demo.jp
      IDM_DISABLE_USER_API_URL: http://idm:8090/IDManager/disabledUserIF?_autoCommit=true
    labels:
      published_name: file-server
      HIVE_MARK: file-server
      webgate:
        authentication: saml
        proxies:
          - target_port: 4200
            maxBodySize: 500
            pathPattern: /
            useWebSocket: "true"
  ftp-server:
    image: ghcr.io/procube-open/nsag-ftp-server:1.0.3-rc.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
      PASV_IP: "192.168.0.4"
      PASV_PORT_MIN: "30000"
      PASV_PORT_MAX: "30003"
    ports:
      - "21:21"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
    labels:
      HIVE_VIP: null
    placement:
      constraints:
        - "{{ 'node.hostname == hive0' if hive_stage == 'production' else 'node.hostname == s-hive0' }}"
  sftpserver:
    image: ghcr.io/procube-open/nsag-sftp-server:1.0.1-rc.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      SFTP_SERVER_PORT: "8822"
      DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
      SERVER_PRIVATE_KEY: "{{ credentials['sftp_server_key'] }}"
    ports:
      - "8822:8822"
  files-db:
    image:
      from: mongo
      roles:
        - python-aptk
        - fileserver-initdb
    environment:
      MONGO_INITDB_DATABASE: files_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - source: files-db
        target: /data/db
        type: volume
        drbd:
          fstype: xfs
          size: 20G
      - source: files-configdb
        target: /data/configdb
        type: volume
        drbd:
          fstype: xfs
          size: 100M
    backup_scripts:
      - name: files_db
        container: files-db
        backup_command: "mongodump --uri=mongodb://root:example@localhost:27017/files_db?authSource=admin --gzip --archive=/archive"
        backup_file: "/archive"
        restore_command: "mongorestore --uri=mongodb://root:example@localhost:27017/files_db?authSource=admin --db=files_db --gzip --archive=/archive --drop"
        restore_file: "/archive"
        cleanup_days_before: 3
  webdav-server:
    image: ghcr.io/procube-open/nsag-webdav-server:1.0.3-rc.0
    ports:
      - 2000:2000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
      # WEBDAV_SERVER_PORT: 2000
      # WEBDAV_PUBLIC_VOLUME_USERNAME: public
    placement:
      constraints:
        #- "{{ 'node.hostname == hive1' if hive_stage == 'production' else 'node.hostname == s-hive1' }}"
        - "{{ 'node.hostname == hive0' if hive_stage == 'production' else 'node.hostname == s-hive0' }}"
    labels:
      HIVE_VIP: null
  session-manager:
    image:
      from: python:alpine3.18
      roles:
        - hive-trust-ca
        - session-manager
        - hive-certificate
    entrypoint:
      - /docker-entrypoint.sh
    environment:
      - IMAGE_CHROME: "{{ groups['repository'] | intersect(groups[hive_stage]) | first }}:5000/image_chrome:latest"
      - WEBDAV_SERVER: "192.168.0.69"
      - WEBDAV_PORT: "2000"
      - WEBDAV_PASSWORD: "test"
      - GUACAMOLE_URL: "http://guacamole:8080/guacamole"
      - GUACAMOLE_USERNAME: "guacadmin"
      - GUACAMOLE_PASSWORD: "guacadmin"
      - GUAC_DATABASE: "postgresql"
      - VNC_PORT: "5900"
      - VNC_PASSWORD: "secret"
      - MEMCACHED_URL: "sm-memcached:11211"
      - SW_LISTENER: "sw-listener"
      - SW_LISTENER_REST: "http://sw-listener:8080"
      - UNAVAILABLE_PORTS: "11443,8080"
      - GET_SWCZONE_URL: "http://idm:8090/IDManager/swcZoneEditIF"
  sm-memcached:
    image: memcached
    endpoint_mode: dnsrr
  scep-server:
    image: 
      from: ghcr.io/procube-open/scep:0.1.3-rc.5
      roles:
        - python-aptk
        - scep-server
    initialize_roles:
      - scep-server-init
    environment:
      - SCEP_DSN: "scep_user:{{ db_password }}@tcp(scep-db:3306)/scep_db?parseTime=true&loc=Asia%2FTokyo"
    ports:
      - "13000:3000"
    volumes:
      - source: scep-download
        target: /app/download
        type: volume
        drbd:
          fstype: xfs
          size: 1G
    labels:
      published_name: scep-server
      HIVE_MARK: scep-server
      webgate:
        proxies:
          - target_port: 3000
            pathPattern: "~ ^/(caweb|admin)"
            authentication: saml
          - target_port: 3000
            postfix: ":api"
            pathPattern: "/api/"
          - target_port: 3000
            postfix: ":scep"
            pathPattern: "/scep"
  scep-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "{{ db_password }}"
      MYSQL_DATABASE: scep_db
      MYSQL_USER: scep_user
      MYSQL_PASSWORD: "{{ db_password }}"
    volumes:
      - source: scep-db
        target: /var/lib/mysql
        type: volume
        drbd:
          fstype: xfs
          size: 1G
  sw-listener:
    image: 
      from: ghcr.io/procube-open/socket-warp:1.1.11-rc.0
      roles: 
        - sw-listener
    ports:
      - target_port: 11443
        published_port: 11443
        protocol: udp
    environment:
      - SWL_CERT_PATH: "{{ swl_cert_path }}/server.crt"
      - SWL_KEY_PATH: "{{ swl_cert_path }}/server.key"
      - SWL_CA_PATH: "{{ swl_ca_path }}/ca.crt"
      - SWL_SCEP_URL: "http://scep-server:3000/api/cert/verify"
    labels:
      published_name: sw-listener
      HIVE_MARK: sw-listener
      webgate:
        proxies:
          - target_port: 11443
            target_protocol: udp
            pathPattern: /
