- name: check for user
  asa_command:
    commands:
      - "show running-config | include username {{ cs_obj[loop_protocol ~ 'ID'] }}"
  vars:
    ansible_connection: network_cli
    ansible_network_os: asa
    ansible_become: yes
    ansible_become_method: enable
  register: result_check_user

- name: create user
  asa_config:
    lines:
      - "username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }} privilege 15"
  vars:
    ansible_connection: network_cli
    ansible_network_os: asa
    ansible_become: yes
    ansible_become_method: enable
  when: result_check_user.stdout[0] | length == 0

- name: update user
  asa_config:
    lines:
      - "username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }}"
  vars:
    ansible_connection: network_cli
    ansible_network_os: asa
    ansible_become: yes
    ansible_become_method: enable
  when: result_check_user.stdout[0] | length > 1

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local

- name: config save
  asa_command:
    commands: 'write mem'
  vars:
    ansible_connection: network_cli
    ansible_network_os: asa
    ansible_become: yes
    ansible_become_method: enable
