- name: check user
  raw: cat /etc/passwd
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('search', search_string) }}"
  vars:
    search_string: "{{ cs_obj[loop_protocol ~ 'ID']}}:x:"

- name: create user
  raw: |
    sudo /usr/sbin/adduser {{ cs_obj[loop_protocol ~ 'ID'] }}
    echo "{{ cs_obj[loop_protocol ~ 'ID'] }}:{{ cs_obj[loop_protocol ~ 'Password'] }}" | sudo /usr/sbin/chpasswd
    sudo /usr/sbin/usermod -a -G wheel {{ cs_obj[loop_protocol ~ 'ID'] }}
  when: result_check_user | length == 0

- name: update password
  raw: |
    echo "{{ cs_obj[loop_protocol ~ 'ID'] }}:{{ cs_obj[loop_protocol ~ 'Password'] }}" | sudo /usr/sbin/chpasswd
  when: result_check_user | length > 0

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local
