- name: check user
  raw: show system admin
  ignore_errors: yes
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('search', search_string) }}"
  vars:
    search_string: ".*{{ cs_obj[loop_protocol ~ 'ID']}}.*"

- name: create user
  raw: |
    config system admin
    edit "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    set access-profile super_admin_prof
    set password "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    next
    end
    exit
  ignore_errors: yes
  when: result_check_user | length == 0

- name: update password
  raw: |
    config system admin
    edit "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    set password "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    next
    end
    exit
  ignore_errors: yes
  when: result_check_user | length > 0

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local
