- name: check user
  cli_command:
    command: |
      configure
      show system login user {{ cs_obj[loop_protocol ~ 'ID'] }}
  register: result_check_user
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios

- name: Extract lines containing a specific string
  set_fact:
    encrypted_password: authentication encrypted-password {{ u_pass }}
    command_for_user: set system login user {{ u_name }}
  vars:
    u_name: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    u_pass: "{{ cs_obj[loop_protocol ~ 'Password'] | password_hash('sha512') }}"

- name: create user
  cli_command:
    command: |
      configure
      {{ command_for_user }} class super-user {{ encrypted_password }}
      commit
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
  when: result_check_user.stdout_lines | length < 10

- name: update user
  cli_command:
    command: |
      configure
      {{ command_for_user }} {{ encrypted_password }}
      commit
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
  when: result_check_user.stdout_lines | length > 10

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local

