# vdom利用時修正が必要！
- name: check user
  raw: |
    show system admin "{{ cs_obj[loop_protocol ~ 'ID'] }}"
  register: result_check_user

- name: create user
  raw: |
    config system admin
    edit "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    set accprofile "super_admin"
    set vdom "root"
    set password "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    next
    end
    exit
  when: result_check_user.stdout_lines | length < 5

- name: update password
  raw: |
    config system admin
    edit "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    set password "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    next
    end
    exit
  when: result_check_user.stdout_lines | length > 7

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local
