- name: update connection
  ansible.netcommon.telnet:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - "login :"
    password_prompt:
      - "Password :"
    prompts:
      - ">"
    commands:
      - show username
      - "#telnet login admin-exec"
    timeout: 10

