- name: check user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - term len 0
      - show running-config | include username
    timeout: 10
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('match', search_string) }}"
  vars:
    search_string: "username {{ cs_obj[loop_protocol ~ 'ID']}} "

- name: create user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - configure terminal
      - username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }} role admin
      - end
    timeout: 10
  when: result_check_user | length == 0

- name: update user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - configure terminal
      - username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }} encryption-level 0
      - end
    timeout: 10
  when: result_check_user | length > 0

- name: update connection
  ansible.netcommon.telnet_aoi:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    commands:
      - "!telnet login admin-exec"
    timeout: 10

- name: check vcs mode
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - show vcs
    timeout: 10
  register: command_output2

- name: Extract lines containing a specific string
  set_fact:
    result_vcs_mode: "{{ command_output2.stdout_lines | select('search', search_string) }}"
  vars:
    search_string: "Fabric Cluster"

- name: save config
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - copy running-config startup-config
    timeout: 10
  when: result_vcs_mode | length > 0
