- name: check user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - 'login: '
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - terminal more disable
      - show account
    timeout: 10
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('match', search_string) }}"
  vars:
    search_string: "account administrator username {{ cs_obj[loop_protocol ~ 'ID']}}"

- name: create user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - 'login: '
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - configure terminal
      - account administrator username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }} secret
      - exit
    timeout: 10
  when: result_check_user | length == 0

- name: update user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - 'login: '
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    command:
      - configure terminal
      - account administrator username {{ cs_obj[loop_protocol ~ 'ID'] }} password {{ cs_obj[loop_protocol ~ 'Password'] }} secret
      - exit
    timeout: 10
  when: result_check_user | length > 0

- name: update connection
  ansible.netcommon.telnet_aoi:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - 'login: '
    password_prompt:
      - "Password:"
    prompts:
      - "#"
    commands:
      - "!telnet login admin-exec"
    timeout: 10

- name: config save
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - 'login: '
    password_prompt:
      - "Password:"
    prompts:
      - "[#:]"
    command:
      - write memory config all
      - "yes"
    timeout: 10
