- name: check user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "Username:"
    password_prompt:
      - "Password:"
    prompts:
      - ">"
    command:
      - display current-configuration | include user
    timeout: 10
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('match', search_string) }}"
  vars:
    search_string: "user {{ cs_obj[loop_protocol ~ 'ID']}}"

- name: create user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "Username:"
    password_prompt:
      - "Password:"
    prompts:
      - ">|]"
    command:
      - system-view
      - aaa
      - "local-user {{ cs_obj[loop_protocol ~ 'ID'] }} password cipher {{ cs_obj[loop_protocol ~ 'Password'] }}"
      - "local-user {{ cs_obj[loop_protocol ~ 'ID'] }} service-type ftp terminal telnet ssh"
      - "local-user {{ cs_obj[loop_protocol ~ 'ID'] }} level 3"
      - "local-user {{ cs_obj[loop_protocol ~ 'ID'] }} ftp-directory flash:"
      - commit
      - return
    timeout: 10
  when: result_check_user | length == 0

- name: update user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "Username:"
    password_prompt:
      - "Password:"
    prompts:
      - ">|]"
    command:
      - system-view
      - aaa
      - "local-user {{ cs_obj[loop_protocol ~ 'ID'] }} password cipher {{ cs_obj[loop_protocol ~ 'Password'] }}"
      - commit
      - return
    timeout: 10
  when: result_check_user | length > 0

- name: update connection
  ansible.netcommon.telnet_aoi:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - "Username:"
    password_prompt:
      - "Password:"
    prompts:
      - ">"
    commands:
      - enable
      - "!telnet login admin-exec"
    timeout: 10

- name: config save
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "Username:"
    password_prompt:
      - "Password:"
    prompts:
      - "[>:]"
    command:
      - save
      - "y"
    timeout: 60

