- name: check user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    clrf: "True"
    login_prompt:
      - "Login:"
    password_prompt:
      - "Password:"
    prompts:
      - "# |User name -----|Enter Pass ----|Re-enter Pass -"
    command:
      - user show
    timeout: 10
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('match', search_string) }}"
  vars:
    search_string: "username {{ cs_obj[loop_protocol ~ 'ID']}}"

- name: create user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    clrf: "True"
    login_prompt:
      - "Login:"
    password_prompt:
      - "Password:"
    prompts:
      - "# |User name -----|Enter Pass ----|Re-enter Pass -"
    command:
      - "user delete user5"
      - "user add user5 read-write"
      - "{{ cs_obj[loop_protocol ~ 'ID'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  when: result_check_user | length == 0

- name: update user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    clrf: "True"
    login_prompt:
      - "Login:"
    password_prompt:
      - "Password:"
    prompts:
      - "# |User name -----|Enter Pass ----|Re-enter Pass -"
    command:
      - "user delete user5"
      - "user add user5 read-write"
      - "{{ cs_obj[loop_protocol ~ 'ID'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  when: result_check_user | length > 0

- name: update connection
  ansible.netcommon.telnet_aoi:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    clrf: "True"
    login_prompt:
      - "Login:"
    password_prompt:
      - "Password:"
    prompts:
      - "# |User name -----|Enter Pass ----|Re-enter Pass -"
    commands:
      - "!telnet login admin-exec"
    timeout: 10

- name: config save
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    clrf: "True"
    login_prompt:
      - "Login:"
    password_prompt:
      - "Password:"
    prompts:
      - "# |User name -----|Enter Pass ----|Re-enter Pass -"
    command:
      - file-create bu
    timeout: 10

