- name: check user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "[>#]|.*[Pp]assword:"
    command:
      - set terminal pager disable
      - enable
      - "P@ssw0rd"
      - cat /etc/passwd
    timeout: 10
  register: command_output

- name: Extract lines containing a specific string
  set_fact:
    result_check_user: "{{ command_output.stdout_lines | select('search', search_string) }}"
  vars:
    search_string: "{{ cs_obj[loop_protocol ~ 'ID']}}"

- name: create user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "[>#]|.*[Pp]assword:"
    command:
      - enable
      - "P@ssw0rd"
      - "adduser {{ cs_obj[loop_protocol ~ 'ID'] }}"
      - ""
      - ""
      - cat /etc/passwd
    timeout: 30
  when: result_check_user | length == 0
- name: create user password
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "[>#]|.*[Pp]assword:"
    command:
      - enable
      - "P@ssw0rd"
      - "password {{ cs_obj[loop_protocol ~ 'ID'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - cat /etc/passwd
    timeout: 30
  when: result_check_user | length > 0

- name: update user
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "[>#]|.*[Pp]assword:"
    command:
      - enable
      - "P@ssw0rd"
      - "password {{ cs_obj[loop_protocol ~ 'ID'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - "{{ cs_obj[loop_protocol ~ 'Password'] }}"
      - cat /etc/passwd
    timeout: 10
  when: result_check_user | length > 0

- name: update connection
  ansible.netcommon.telnet_aoi:
    username: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - "login: "
    password_prompt:
      - "Password:"
    prompts:
      - "[>#]|.*[Pp]assword:"
    commands:
      - enable
      - "P@ssw0rd"
      - cat /etc/passwd
    timeout: 30
