---
- name: setup python3
  apk:
    name:
    - python3
    - py3-openssl
    - py3-cryptography
- name: "put CA certificate"
  copy:
    src: "{{ hive_safe_ca_dir }}/cacert.pem"
    dest: "{{ ca_path }}/ca.crt"
    mode: 0644
- name: "put CA key"
  copy:
    src: "{{ hive_safe_ca_dir }}/cakey.pem"
    dest: "{{ ca_path }}/ca_pkcs8.key"
    mode: 0644
- name: "Convert private key from PKCS#8 to PKCS#1 format"
  community.crypto.openssl_privatekey_convert:
    src_path: "{{ ca_path }}/ca_pkcs8.key"
    dest_path: "{{ ca_path }}/ca.key"
    format: pkcs1
- name: "make download directory"
  file:
    path: "{{ download_dir }}"
    state: directory
    mode: 0755