# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from task_executer.models.base_model_ import Model
from task_executer import util


class EnumDefinition(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, display_name=None, description=None):  # noqa: E501
        """EnumDefinition - a model defined in OpenAPI

        :param value: The value of this EnumDefinition.  # noqa: E501
        :type value: str
        :param display_name: The display_name of this EnumDefinition.  # noqa: E501
        :type display_name: str
        :param description: The description of this EnumDefinition.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'value': str,
            'display_name': str,
            'description': str
        }

        self.attribute_map = {
            'value': 'value',
            'display_name': 'displayName',
            'description': 'description'
        }

        self._value = value
        self._display_name = display_name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'EnumDefinition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _enumDefinition of this EnumDefinition.  # noqa: E501
        :rtype: EnumDefinition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self):
        """Gets the value of this EnumDefinition.

        列挙される値 - ドロップダウンリストでこの選択肢が選ばれると、この値が属性の値となる。  # noqa: E501

        :return: The value of this EnumDefinition.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this EnumDefinition.

        列挙される値 - ドロップダウンリストでこの選択肢が選ばれると、この値が属性の値となる。  # noqa: E501

        :param value: The value of this EnumDefinition.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def display_name(self):
        """Gets the display_name of this EnumDefinition.

        列挙値の表示名 - ドロップダウンリストに表示される名前。この値が null の場合は、値が表示される。  # noqa: E501

        :return: The display_name of this EnumDefinition.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this EnumDefinition.

        列挙値の表示名 - ドロップダウンリストに表示される名前。この値が null の場合は、値が表示される。  # noqa: E501

        :param display_name: The display_name of this EnumDefinition.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def description(self):
        """Gets the description of this EnumDefinition.

        列挙値の説明 - ドロップダウンリストやヘルプに表示される説明文  # noqa: E501

        :return: The description of this EnumDefinition.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EnumDefinition.

        列挙値の説明 - ドロップダウンリストやヘルプに表示される説明文  # noqa: E501

        :param description: The description of this EnumDefinition.
        :type description: str
        """

        self._description = description
