- name: read definitions
  idm_fact:
    interface: "{{ md_if.name }}"
    filter: "{{ md_if.filter | default(omit) }}"
  register: md_data
- name: put documents for definitions
  local_action:
    module: template
    src: "{{ md_if.src }}"
    dest: "{{ hive_root_dir }}/docs/{{ md_if.dest }}"
